### ISSUE TITLE
Version 3.1.0 compiled with Java 8

### ISSUE THREAD

**Issue by bschelberg** [jenkinsci/selenium-plugin#103]
Version 3.1.0 seems to have been compiled with Java 8:
```
WARNING: Loading plugin Jenkins Selenium Plugin v3.1.0 (selenium) failed perhaps due to plugin dependency issues
java.io.IOException: Unable to load hudson.plugins.selenium.PluginImpl from selenium
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:508)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:517)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedClassVersionError: hudson/plugins/selenium/PluginImpl : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
        at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:876)
        at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1363)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:501)
        ... 9 more
```

I don't know if this was intentional or not. If it was, a note on the changelog would be good.

**Comment by Mobrockers** [comment]
This was intentional, and there should be a note in the plugin wiki page.

**Comment by bschelberg** [comment]
Right, I see that now. I generally don't read the wiki page when upgrading plugins, just skip down to the changelog to check that.

**Comment by Mobrockers** [comment]
I added a warning to the plugin summary as well, I expected that warning to show up on the plugin upgrade page. Did it not?

**Comment by bschelberg** [comment]
No, there was no warning on the plugin upgrade page. I don't know if it makes a difference, but we're using the LTS 2.32.3 version.

**Comment by Mobrockers** [comment]
I'm sorry :/ jenkins does not have a good way to warn for these things yet. I'll add it to the changelog too tho.
