### ISSUE TITLE
selenium Plugin fails to reconnect when Jenkins restarts or the corresponding server reboots

### ISSUE THREAD

**Issue by naveen0725** [jenkinsci/selenium-plugin#122]
Hello, I have already posted my question here at https://wiki.jenkins.io/display/JENKINS/Selenium+Plugin
with Naveen M as a user. 

If it can be resolved, that would be great.

**Comment by jameswtelfer** [comment]
From the logs you've posted it looks like you're running into a similar issue I had under #118.

For the fix to that see https://wiki.jenkins.io/display/JENKINS/Slave+To+Master+Access+Control.

**Comment by naveen0725** [comment]
Thank you jameswtelfer for your reply on my post, so your mentioned solution didn't resolved completely as I was still getting 
"ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
java.lang.NullPointerException". 

and I found something here for above error  - https://issues.jenkins-ci.org/browse/JENKINS-25583 and tried the first solution but didn't helped

This issue seems to be resolved already version 2.x,but still finding a issue.

can anyone help me on this to resolve it completely?


New  error  log :

[05/21/18 09:26:42] [SSH] Starting sftp client.
[05/21/18 09:26:42] [SSH] Copying latest slave.jar...

[05/21/18 09:26:42] [SSH] Copied 770,772 bytes.
Expanded the channel window size to 4MB
[05/21/18 09:26:42] [SSH] Starting slave process: cd "/var/jenkins" && /opt/jdk1.8.0_144/bin/java -Xms2048m -Xmx2048m -Dhudson.util.ProcessTree.disable=true -jar slave.jar

<===[JENKINS REMOTING CAPACITY]===>channel started

Remoting version: 3.19
This is a Unix agent

Evacuated stdout
Starting Selenium nodes on xxxxxxxxxxxx
ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
java.lang.NullPointerException
	at hudson.plugins.selenium.configuration.CustomWDConfiguration.initOptions(CustomWDConfiguration.java:136)
	at hudson.plugins.selenium.process.SeleniumJarRunner.start(SeleniumJarRunner.java:37)
	at hudson.plugins.selenium.configuration.global.SeleniumGlobalConfiguration.start(SeleniumGlobalConfiguration.java:50)
	at hudson.plugins.selenium.PluginImpl.startSeleniumNode(PluginImpl.java:503)
	at hudson.plugins.selenium.ComputerListenerImpl.onOnline(ComputerListenerImpl.java:30)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:620)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:416)
	at hudson.plugins.sshslaves.SSHLauncher.startSlave(SSHLauncher.java:1110)
	at hudson.plugins.sshslaves.SSHLauncher.access$500(SSHLauncher.java:148)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:845)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:820)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[05/21/18 09:26:46] Launch failed - cleaning up connection
[05/21/18 09:26:46] [SSH] Connection closed.
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2675)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3150)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:859)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:355)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
