### ISSUE TITLE
Error executing only with chromedriver

### ISSUE THREAD

**Issue by miguelconde91** [jenkinsci/selenium-plugin#137]
Hello, I have installed the plugin in my jenkins server, the tests using geckodriver works fine, however using chromedriver I have this error in my jobs execution:

Traceback (most recent call last):
  File "./test_sele.py", line 23, in setUp
    desired_capabilities=desired_caps)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-1023-aws x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 321 milliseconds
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'ip-172-31-#-#', ip: '172.31.#.#', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1023-aws', java.version: '1.8.0_181'
Driver info: driver.version: unknown

In the node that execute the test I have this log:

21:16:43.435 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "platform": "LINUX"
}
21:16:43.436 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d) on port 2872
Only local connections are allowed.

In this node I have:
Google Chrome 70.0.3538.77 and
ChromeDriver 2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d)

This versions are compatibles, my node is not the same EC2 (because I'm using AWS) that the hub. I can run Jobs using firefox like browserName. The error is the same if I execute the test local in the node a not through my jenkins job, so the problem is local in the node of my Selenium grid. How to fix the problem if geckodriver work why chromedriver not?

**Comment by miguelconde91** [comment]
If I use-> DISPLAY=:99 python test_selenium.py and if in my file I have this line-> driver = webdriver.Chrome(executable_path="/usr/local/bin/chromedriver", service_args=["--verbose", "--log-path=./mylog"]) it's works, however I'm using Selenium Grid, I can not use the line with the chrome executable. I think that is not a problem of selenium-plugin, is problem of chromedriver that not recognize the DISPLAY environment variable. Xvfb is running with Xvfb :99 -ac -screen 0 1024x768x8 & export DISPLAY=":99", with that it's enough for geckodriver to function, but to chromedriver not
