### ISSUE TITLE
WARNING: Proxy 'host :http://x.x.x.x:4445 time out : 300000' was previously registered.  Cleaning up any stale test sessions

### ISSUE THREAD

**Issue by santigimeno** [jenkinsci/selenium-plugin#28]
After running successfully a job that uses the selenium plugin, I always get this error in the selenium log and then there are not registered RC.
In the jenkins log I get this error:

May 17, 2013 1:33:05 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel Channel to Selenium RC
java.io.IOException: Unexpected termination of the channel
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2553)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1296)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
        at hudson.remoting.Command.readFrom(Command.java:92)
        at hudson.remoting.ClassicCommandTransport.read(ClassicCommandTransport.java:59)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

The only way I've found to recover from this is to restart jenkins. Any ideas what might be causing this?

Thanks

**Comment by Mobrockers** [comment]
Is this issue still present in the latest plugin version?
