### ISSUE TITLE
How do you configure the node to run the correct firefox and chromedriver binaries?

### ISSUE THREAD

**Issue by sr3d** [jenkinsci/selenium-plugin#5]
I'm setting up a new CI server and I wonder how can the plugin start the correct firefox binary?  This is what I got from the log:

19:45:09.191 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 09:56:25'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.21.7-2.fc8xen', java.version: '1.6.0_14'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:139)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:108)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:86)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:87)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:49)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:196)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:586)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:523)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:490)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1530)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1482)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:909)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 09:56:25'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.21.7-2.fc8xen', java.version: '1.6.0_14'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:73)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:57)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:177)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:63)
	... 8 more
Caused by: org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 09:56:25'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.21.7-2.fc8xen', java.version: '1.6.0_14'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.Executable.<init>(Executable.java:54)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:52)
	at org.openqa.selenium.firefox.FirefoxDriver.getBinary(FirefoxDriver.java:133)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:87)
	... 13 more
19:45:09.204 WARN - Exception: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: LINUX
Build info: version: '2.15.0', revision: '15105', time: '2011-12-08 09:56:25'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.21.7-2.fc8xen', java.version: '1.6.0_14'
Driver info: driver.version: FirefoxDriver

**Comment by Mobrockers** [comment]
@zeroem was this issue still present in the last version?

**Comment by Mobrockers** [comment]
@zeroem the fix has been added a long time ago but no release was made. I will hopefully release tonight.
