### ISSUE TITLE
Cannot create package from master

### ISSUE THREAD

**Issue by janaurka** [jenkinsci/selenium-plugin#58]
Hey

When I try to do `mvn package` from current master, the build fails.

```
mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Jenkins Selenium Plugin 2.4.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-hpi-plugin:1.106:validate (default-validate) @ selenium ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0.1:enforce (enforce-maven) @ selenium ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0.1:display-info (display-info) @ selenium ---
[INFO] Maven Version: 3.0.4
[INFO] JDK Version: 1.8.0_72 normalized as: 1.8.0-72
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 3.2.0-24-generic
[INFO]
[INFO] --- maven-localizer-plugin:1.14:generate (default) @ selenium ---
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ selenium ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 95 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5:compile (default-compile) @ selenium ---
[INFO] Compiling 27 source files to /home/jan/selenium-plugin/target/classes
[INFO]
[INFO] --- access-modifier-checker:1.7:enforce (default-enforce) @ selenium ---
[INFO]
[INFO] --- maven-hpi-plugin:1.106:insert-test (default-insert-test) @ selenium ---
[INFO]
[INFO] --- gmaven-plugin:1.5-jenkins-1:generateTestStubs (test-in-groovy) @ selenium ---
[INFO] No sources found for Java stub generation
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ selenium ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jan/selenium-plugin/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5:testCompile (default-testCompile) @ selenium ---
[INFO] Compiling 1 source file to /home/jan/selenium-plugin/target/test-classes
[INFO]
[INFO] --- maven-hpi-plugin:1.106:test-hpl (default-test-hpl) @ selenium ---
[INFO] Generating /home/jan/selenium-plugin/target/test-classes/the.hpl
[INFO]
[INFO] --- maven-hpi-plugin:1.106:resolve-test-dependencies (default-resolve-test-dependencies) @ selenium ---
[INFO]
[INFO] --- gmaven-plugin:1.5-jenkins-1:testCompile (test-in-groovy) @ selenium ---
[INFO] No sources found to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ selenium ---
[WARNING] The parameter forkMode is deprecated since version 2.14. Use forkCount and reuseForks instead.
[WARNING] useSystemClassloader setting has no effect when not forking
[INFO] Surefire report directory: /home/jan/selenium-plugin/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running hudson.plugins.selenium.SeleniumTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 48.423 sec <<< FAILURE! - in hudson.plugins.selenium.SeleniumTest
testSelenium1(hudson.plugins.selenium.SeleniumTest)  Time elapsed: 23.359 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: TypeError: Cannot find function addEventListener in object [object Window]. (https://jenkins.io/assets/bower/tether/js/tether.min.js#1)
Command duration or timeout: 4.31 seconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'leto', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-24-generic', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{webdriver.remote.sessionid=e35cc643-33e5-4b67-9d59-9d778694d8da, browserName=htmlunit, javascriptEnabled=true, version=null, cssSelectorsEnabled=true, platform=LINUX}]
Session ID: e35cc643-33e5-4b67-9d59-9d778694d8da
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:306)
	at hudson.plugins.selenium.SeleniumTest.testSelenium1(SeleniumTest.java:95)
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: TypeError: Cannot find function addEventListener in object [object Window]. (https://jenkins.io/assets/bower/tether/js/tether.min.js#1)
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'leto', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-24-generic', java.version: '1.8.0_72'
Driver info: driver.version: EventFiringWebDriver
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3935)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3919)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3944)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3960)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4027)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2426)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2408)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1337)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
	at net.sourceforge.htmlunit.corejs.javascript.NativeArray.iterativeMethod(NativeArray.java:1687)
	at net.sourceforge.htmlunit.corejs.javascript.NativeArray.execIdCall(NativeArray.java:405)
	at net.sourceforge.htmlunit.corejs.javascript.IdFunctionObject.call(IdFunctionObject.java:93)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1536)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:411)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3286)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:721)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:832)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:730)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1096)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:395)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:270)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:290)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:793)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:751)
	at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
	at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
	at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
	at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3126)
	at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2093)
	at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:920)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
	at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:1017)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:248)
	at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:194)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
	at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
	at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:471)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:345)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:410)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:512)
	at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
	at com.sun.proxy.$Proxy18.get(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:160)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
	at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Running InjectedTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.263 sec - in InjectedTest

Results :

Tests in error:
  SeleniumTest.testSelenium1:95 » WebDriver TypeError: Cannot find function addE...

Tests run: 45, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:02.072s
[INFO] Finished at: Thu Apr 14 17:05:05 CEST 2016
[INFO] Final Memory: 58M/1530M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project selenium: There are test failures.
[ERROR]
[ERROR] Please refer to /home/jan/selenium-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Building the latest `release` which is `selenium-2.4.1` works.

System information:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
$ mvn --version
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-24-generic", arch: "amd64", family: "unix"
```

**Comment by Mobrockers** [comment]
Pull the latest changes and try again. It should build fine now.

**Comment by janaurka** [comment]
I’m able to build on a `OSX 10.10`. thx for solving the bug & updating the plugin!
