### ISSUE TITLE
Selenium Plugin 2.53.0 causes NullPointerException on Jenkins startup

### ISSUE THREAD

**Issue by LukeHackett** [jenkinsci/selenium-plugin#78]
Hello All,

We've recently upgraded to the latest version of Selenium Plugin (2.53.0) from 2.4.1.
Jenkins throws a null pointer exception (See stack trace below) on start up preventing Jenkins from starting up.

V2.4.1 was working fine before, I couldn't see any issues in the notes that may cause our problem. We're running Jenkins on Centos 6.4 and Java 1.8.0_25.

We've tried upgrading Jenkins from 1.6 to 2.1 (thinking it was Jenkins being a bit outdated) and we're still seeing the null pointer exception.

Any help would be much welcomed, and I can provide additional details should you require them.

```
hudson.util.HudsonFailedToLoad: java.lang.NullPointerException
	at hudson.WebAppMain$3.run(WebAppMain.java:238)
Caused by: java.lang.NullPointerException
	at hudson.plugins.selenium.configuration.CustomWDConfiguration.initOptions(CustomWDConfiguration.java:117)
	at hudson.plugins.selenium.process.SeleniumJarRunner.start(SeleniumJarRunner.java:38)
	at hudson.plugins.selenium.configuration.global.SeleniumGlobalConfiguration.start(SeleniumGlobalConfiguration.java:47)
	at hudson.plugins.selenium.PluginImpl.startSeleniumNode(PluginImpl.java:485)
	at hudson.plugins.selenium.ComputerListenerImpl.onOnline(ComputerListenerImpl.java:26)
	at jenkins.model.Jenkins.<init>(Jenkins.java:910)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:226)
```

**Comment by Mobrockers** [comment]
Jenkins seems to have some issues converting the plugin configuration to the new format (after some options were added) and I do not know how to manage this (convert during upgrade?). I think deleting the selenium configuration would fix your issue. Could you try removing the configuration file?

The configuration file is in %JENKINS_HOME% and is called selenium.xml

**Comment by LukeHackett** [comment]
Hi @Mobrockers,

Thanks for the advice, we've followed, and our Jenkins appears to be back up running normally. 
Many thanks for your help.
